### ISSUE TITLE
Wrong package from package control

### ISSUE THREAD

**Issue by SebCav** [SublimeLinter/SublimeLinter-erlc#4]
Hello,
on my systems (both Windows and Linux) Package Control seems to download the wrong package for this linter plugin. I choose to install SublimeLinter-erlc but the package that gets installed is the old SublimeLinter-contrib-erlc which does not work anymore.
Do you have any suggestion? The only solution I found is to manually build the plugin and replace it every time Package Control re-downloads the wrong version...
Thank you

**Comment by braver** [comment]
Well that is weird. Let's try this:
- remove the package via package control
- remove your manual installation of the package
- restart Sublime Text
- install SublimeLinter-erlc via package control
- report back with the contents of your package control user settings (it contains a list of installed packages)
- install PackageResourceViewer via package control
- run "Open Resource" on "SublimeLinter-erlc" and then "linter.py" and tell us what the contents of linter.py are

**Comment by SebCav** [comment]
Here is the result from a Windows system where I never installed the plugin manually. 

Package control message when installing the plugin:

```
Package Control Messages
========================

SublimeLinter-erlc
------------------

  SublimeLinter-contrib-erlc
  -------------------------------
  This linter plugin for SublimeLinter provides an interface to erlc.
  
  ** IMPORTANT! **
  
  Before this plugin will activate, you *must*
  follow the installation instructions here:
  
  https://github.com/teh-cmc/SublimeLinter-contrib-erlc
```

Package control user settings, with also the error on loading the erlc plugin:

![sublime](https://user-images.githubusercontent.com/23406539/63758651-6840e100-c8bc-11e9-95fd-eadff093e30c.jpg)

And the linter.py file is clearly the one from the old package

```
###
# Erlang linter plugin for SublimeLinter3
# Uses erlc, make sure it is in your PATH
#
# Copyright (C) 2014  Clement 'cmc' Rey <cr.rey.clement@gmail.com>
#
# MIT License
###

"""This module exports the Erlc plugin class."""

from SublimeLinter.lint import Linter, util


class Erlc(Linter):
    """Provides an interface to erlc."""

    syntax = (
        "erlang",
        "erlang improved"
    )

    executable = "erlc"
    tempfile_suffix = "-"

    # ERROR FORMAT # <file>:<line>: [Warning:|] <message> #
    regex = (
        r".+:(?P<line>\d+):"
        r"(?:(?P<warning>\sWarning:\s)|(?P<error>\s))"
        r"+(?P<message>.+)"
    )

    error_stream = util.STREAM_STDOUT

    defaults = {
        "include_dirs": []
    }

    def cmd(self):
        """
        return the command line to execute.

        this func is overridden so we can handle included directories.
        """
        command = ['erlc', '-W']

        settings = self.get_view_settings()
        dirs = settings.get('include_dirs', [])
        pa_dirs = settings.get('pa_dirs', [])
        pz_dirs = settings.get('pz_dirs', [])
        output_dir = settings.get('output_dir', ".")

        for d in dirs:
            command.extend(["-I", d])

        for d in pa_dirs:
            command.extend(["-pa", d])

        for d in pz_dirs:
            command.extend(["-pz", d])

        command.extend(["-o", output_dir])

        command.extend(["$file_on_disk"])

        return command
```

**Comment by braver** [comment]
Ok, for whatever reason package control is not picking up on the new repo. I'll have to look into this.

**Comment by jwheare** [comment]
That's the new repo, just 1.1.0, package control hasn't picked up the 1.2.0 you just released yet.

**Comment by braver** [comment]
Indeed. Usually takes about an hour for PC to pick up a release, it could be any minute now.

**Comment by SebCav** [comment]
This is quite confusing, the tag 1.2.0 is on a commit dated August 24, but you say you just released it... I'll wait until tomorrow and report back.

**Comment by braver** [comment]
It's on a commit from a few days ago, but the tag itself is fresh. I sure hope it picks up on it soon, it's not very easy to debug package control issues.

**Comment by jwheare** [comment]
1.2.0 is now showing up on https://packagecontrol.io/packages/SublimeLinter-erlc

**Comment by braver** [comment]
I guess that little housekeeping I did on the package control channel didn't work out. Ah well..

**Comment by SebCav** [comment]
Confirmed, Package Control now installs 1.2.0 and it works. Thank you
