### ISSUE TITLE
how can i use the include_dirs tag?

### ISSUE THREAD

**Issue by derekuang** [SublimeLinter/SublimeLinter-erlc#5]
i have installed the plugin sublimelinter and sublimelinter-erlc, but the linter seems not able to find the include directory.
how can i make it work?

**Comment by kaste** [comment]
Have you already tried something?  If not, start by opening the SublimeLinter settings. Here add a key erlc under linters. Below that a key include_dirs mapped to an array of directories. That's a first start. Usually you want project specific settings though. In the Readme here in this project you'll find some links.

**Comment by derekuang** [comment]
> 
> 
> Have you already tried something? If not, start by opening the SublimeLinter settings. Here add a key erlc under linters. Below that a key include_dirs mapped to an array of directories. That's a first start. Usually you want project specific settings though. In the Readme here in this project you'll find some links.

thx! problem solved!
