### ISSUE TITLE
OTP24 now includes column numbers, confusing the line number

### ISSUE THREAD

**Issue by mworrell** [SublimeLinter/SublimeLinter-erlc#6]
In OTP24 the error line looks like:

```
/Users/marc/zotonic_core/src/models/m_rsc_import.erl:227:59: Warning: variable 'Context' is unused
```

Note the `:line:column:` in the error messages.

This messes with the regexp:

```
r".+:(?P<line>\d+):"
```

It might need an optional column number match, I suspect something like:

```
r".+:(?P<line>\d+)(:\d+)?:"
```

**Comment by zigge-zagge** [comment]
Not backward compatible but a working fork for newer Erlang versions: https://github.com/jyzr/SublimeLinter-erlc/

**Comment by kaste** [comment]
Howdy,  but if that works @zigge-zagge, then shouldn't be `r".+:(?P<line>\d+)(:(?P<col>\d+))?:"` backwards compatible?

**Comment by kaste** [comment]
Usually lazy 🙄 
```
^.+?:(?P<line>\d+)(?::(?P<col>\d+))?:
   ^
```
